{
  "extends": "stylelint-config-sass-guidelines",
  "ignoreFiles": [
    "src/sass/example-page/**",
    "src/sass/vendor/**"
  ],
  "plugins": [
    "stylelint-scss"
  ],
  "defaultSeverity": "warning",
  "rules": {
    "max-nesting-depth": 3,
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    ##### Rules to fix at a later point #####
    "scss/at-extend-no-missing-placeholder": null,
    "selector-class-pattern": null,
    # Vendor Prefixes #
    "property-no-vendor-prefix": null,
    "at-rule-no-vendor-prefix": null,
    "value-no-vendor-prefix": null,
    #
    "selector-no-qualifying-type": null,
    "function-calc-no-unspaced-operator": true
  }
}
