{
  "extends": "stylelint-config-sass-guidelines",
  "ignoreFiles": [
    "src/sass/example-page/**",
    "src/sass/vendor/**"
  ],
  "plugins": [
    "stylelint-scss"
  ],
  "defaultSeverity": "warning",
  "rules": {
    "max-nesting-depth": 3,
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
  }
}
